name: CI
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: 
      - main
defaults:
  run:
    shell: bash

env:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES

jobs:
  fastcore:
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu, macos] #,windows]
        py:  ["3.10", "3.11", "3.12", "3.13"]
        include:
          #- os: windows
          #  shell: "/usr/bin/bash"
          - os: ubuntu 
            shell: "/bin/bash"
          - os: macos 
            shell: "/bin/bash"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        pip install -Uqq --pre nbdev
        pip install -e ".[dev]"
        #- name: Check if notebooks are synced and cleaned
        #uses: fastai/workflows/nb@master
    - name: Run tests
      run: nbdev_test
      env:
        SHELL:  ${{ matrix.shell }}

  nbdev-integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: clone this branch [fastcore]
      uses: actions/checkout@v3
      with:
        path: fastcore_lib
    - name: clone nbdev
      uses: actions/checkout@v3
      with:
        repository: 'fastai/nbdev'
        path: nbdev   
    - name: Install libraries
      run: |
        cd fastcore_lib && pip install -Ue .[dev]
        cd ../nbdev && pip install -Ue .[dev]
    - name: test nbdev notebooks
      run: |
        cd nbdev && nbdev_test
